### ISSUE TITLE
PyPI wheels for Python 3.8

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/BTrees#113]
It would be nice to have Python 3.8 wheels for Windows at least (Linux users tend to have C compilers) published on PyPI.

This can be done with a little extra snippet in appveyor.yml without having to wait for official Appveyor Python 3.8 support: see https://github.com/zopefoundation/persistent/pull/118

**Comment by mgedmin** [comment]
#114 is merged now, so the next release should have 3.8 wheels for Windows and Linux, but not for Mac OS (patches welcome!).

I would prefer to get #115 in before a release purely because of prettier task names in the Travis CI build matrix. ;)

**Comment by mgedmin** [comment]
I've pushed a release, CI should upload wheel files in due time.

**Comment by mgedmin** [comment]
MacOS 2.7 and 3.5 uploads failed with

```
Uploading distributions to https://upload.pypi.org/legacy/
  ...
requests.exceptions.SSLError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /pypi/BTrees/json (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)'),))
```

Does anyone have any idea?

**Comment by jamadden** [comment]
I would have guessed that what we're seeing is related to [pypi requiring TLS 1.2](http://pyfound.blogspot.com/2017/01/time-to-upgrade-your-python-tls-v12.html) and older versions of Python installed on older versions of macOS not understanding that due to an ancient versions of OpenSSL.

- We ask to install 'macpython 2.7' and 'macpython 3.5'. 
- Those [are pinned](https://github.com/matthew-brett/multibuild/blob/7d67726f08cb4ab80c235c5a97ee43b64f6112f1/osx_utils.sh) to the versions available in 2017, 2.7.14 and 3.5.4.
- 2.7.14 linked to the system openssl and thus can't connect to PyPI; this was [changed in 2.7.15](https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.15rc1.rst)
- As far as I can tell from [the bug report](https://bugs.python.org/issue17128) all versions of 3.6 and above have done the same, but Python 3.5 was never updated.

That doesn't pan out, though, because both those versions *were* able to download using pip, just not upload using twine. So I'm not sure...[checks pip release notes]...Oh, [pip 9.1.8](https://pip.pypa.io/en/stable/news/#id226) uses `ctypes` on macOS to enable downloads even when the underlying ssl module doesn't support TLS 1.2. How very thoughtful!

I think if we specify a specific newer version of Python 2.7, uploads should work: 'macpython 2.7.17'. 

There are no newer binary installers for 3.5, so we could try homebrew? Python 3.5 goes end-of-life early next year (February is 5 years since release) so maybe don't bother with 3.5 at all?

**Comment by mgedmin** [comment]
Do we have to use the same Python for twine uploading that we use for builds?  Is there another Python present somewhere in the Mac OS Travis images?  Can we use that one to install and run twine?

We could also try the native Travis pypi upload feature: https://docs.travis-ci.com/user/deployment/pypi/.  It allows arbitrary conditions using bash syntax: https://docs.travis-ci.com/user/deployment#conditional-releases-with-on

**Comment by jamadden** [comment]
> Do we have to use the same Python for twine uploading that we use for builds? Is there another Python present somewhere in the Mac OS Travis images? Can we use that one to install and run twine?

An excellent idea. I tested on my 10.14 system using /usr/bin/python (which is linked to LibreSSL) and this sequence worked to upload:
```console
$ /usr/bin/python -mensurepip --user
$ /usr/bin/python -m pip install -U --user pip
$ /usr/bin/python -m pip install -U --user twine
$ /usr/bin/python -m twine upload ...
```

If that works on 10.13, we're all set.

**Comment by mgedmin** [comment]
> We could also try the native Travis pypi upload feature: https://docs.travis-ci.com/user/deployment/pypi/.

I've been playing with this, and I don't see how to tell it to upload files from `wheelhouse/*.whl`.  I get the impression that the pypi deploy provider wants to run `setup.py sdist bdist_wheel` for you instead of just uploading the wheel files you've already generated.

**Comment by mgedmin** [comment]
Assuming https://github.com/travis-ci/dpl/blob/master/lib/dpl/providers/pypi.rb is the Travis PyPI deploy script, it seems we can upload arbitrary files if we specify `distributions: "--version"` or some other such harmless `setup.py` argument that doesn't build anything, and if we copy the whl files into `dist/` beforehand.

It would look something like this:

```yaml
deploy:
  provider: pypi
  username: zope.wheelbuilder
  password:
    secure: ...
  distributions: --version  # hack not to build anything
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
    condition: '"$TRAVIS_IS_NAME" == osx || -n "$DOCKER_IMAGE"'
```

and at this point I'm not convinced it's better than continuing to pip install and run twine directly.

**Comment by fgregg** [comment]
I switched to github actions to get mac py 3.8 builds.

I also opened an issue on terrify, https://github.com/MacPython/terryfy/issues/20
