### ISSUE TITLE
Tests break on Python 3.5

### ISSUE THREAD

**Issue by domenkozar** [zopefoundation/BTrees#15]
```
ValueError: incomparable                                                                                [0/1943]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/nix-build-python3.5-BTrees-4.1.4.drv-0/BTrees-4.1.4/BTrees/tests/testBTrees.py", line 426, in testF
oo
    t[DoesntLikeBeingCompared()] = None
  File "/tmp/nix-build-python3.5-BTrees-4.1.4.drv-0/BTrees-4.1.4/BTrees/tests/testBTrees.py", line 416, in __cmp
__
    raise ValueError('incomparable')
SystemError: <class 'ValueError'> returned a result with an error set

```

**Comment by tseaver** [comment]
FWIW, the `ValueError('incomparable')` is an *expected* error:  it is being used as part of a test for how BTrees behave when passed objects (like `None`) which cannot be compared.

I don't know why there is a `SystemError` here.  See:

- https://bugs.launchpad.net/ubuntu/+source/pytables/+bug/1478146 (a similar error in PyTables:  I've asked Barry Warsaw to point me to the fix for it).
- https://bugs.launchpad.net/ubuntu/+source/pytables/+bug/1478146 (where the check was introduced)
