### ISSUE TITLE
Pylance has problem resolving imports

### ISSUE THREAD

**Issue by alexreg** [zopefoundation/BTrees#150]
For example, writing

```py
from BTrees.OOBTree import *
```

yields

```
Import "BTrees.OOBTree" could not be resolvedPylancereportMissingImports
```

as a Pylance error (in VS Code). Is there any way to get around this? Is this a bug on your end or Pylance's?

**Comment by mwatts15** [comment]
Assuming you have BTrees installed, I'd guess it's a matter of telling pylance where it's installed (however you do that), but it's very unlikely to be a problem with BTrees itself (I can import it just fine...).

**Comment by jamadden** [comment]
Note that many of the BTree modules are created dynamically and don't exist as files on disk. This confuses some static linters, even though the imports work fine.

One way to avoid problems with such linters is to use the `family` interfaces instead of the modules. Instead of `from BTrees.OOBTree import OOBTree; btree = OOBTree()`, one can write `import BTrees; btree = BTrees.family64.OO.BTree()`

**Comment by alexreg** [comment]
Thanks for the replies. It seems that the dynamic generation of the module is indeed the problem as far as a static analyser like Pylance is concerned.

**Comment by alexreg** [comment]
The `family64` namespace is dynamic too. I think the solution is just to give up on type-checking in this case:

```py3
if TYPE_CHECKING:
	OOBTree = Any
	OOSet = Any
else:
	from BTrees.OOBTree import *
```

**Comment by alexreg** [comment]
Actually, a better solution is:

```py3
if TYPE_CHECKING:
	from BTrees.Interfaces import ISet as OOSet
	from BTrees.Interfaces import IBTree as OOBTree
else:
	from BTrees.OOBTree import *
```

This works pretty nicely and still allows for type checking!
