### ISSUE TITLE
Track tree size explicitly

### ISSUE THREAD

**Issue by enkore** [zopefoundation/BTrees#61]
Currently the size of the tree (`__len__`) is calculated on demand and involves loading and querying all buckets. I think it would be reasonable to track the number of items explicitly (by counting through insertions and deletions), so that querying it doesn't need to load anything except the root BTree object. This only becomes problematic if client code pries out buckets from a tree and manipulates these itself.

Naturally this changes the pickle layout, so it would require extra compat code and would not be backwards compatible.

Perhaps something for a major release?

**Comment by jamadden** [comment]
BTrees do not track their size due to the requirement of handling conflicts, I believe: conflicts would go up substantially, and even if they could be resolved, resolution is a serialized process. But they provide the `BTrees.Length.Length` class that helps handle this.

If you want something that does track its size (using this class) you might consider a [BTree Container](http://zopecontainer.readthedocs.io/en/latest/api.html#zope.container.btree.BTreeContainer)

(Note that subclassing a BTree is not recommended, the "wrapping" approach used by the BTreeContainer is better.)

**Comment by enkore** [comment]
Thanks, I wondered why and that seems to be very plausible. Also thanks for these pointers, they look quite helpful to practical application! :)

**Comment by jamadden** [comment]
Is this sufficiently answered to close then?
